apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
    name: xgboost-job-manual
    namespace: default
spec:
    type: Scala
    mode: cluster
    image: "localhost:5000/xgboost"
    imagePullPolicy: Always
    mainClass: com.dhs.xgboost.XGB
    mainApplicationFile: "local:///opt/spark/work-dir/xgb.jar"
    sparkVersion: "2.4.5"
    restartPolicy:
      type: Never
    volumes:
        -   hostPath:
                path: /data
                type: Directory
            name: spark-data
            
    driver:
        cores: 1
        coreLimit: "1200m"
        memory: "512m"
        labels:
            version: 2.4.5
        serviceAccount: spark
        volumeMounts:
            - name: spark-data
              mountPath: /data
    executor:
        cores: 2
        instances: 2
        memory: "512m"
        labels:
            version: 2.4.5
        volumeMounts:
            -   name: spark-data
                mountPath: /data